### ISSUE TITLE
Missing documentation and not released to npm

### ISSUE THREAD

**Issue by technicalpickles** [luijose/hubot-9gag#1]
Had a question on #hubot from @thorsonmscott about using this script. It was extracted from hubot-scripts, but didn't have any notes on how to install in README, and it didn't seem to be be published to npm. This makes it pretty tough for folks to get started using this script.

Let me know if you'd like me to do the actual npm publish, and I can add you as a collaborator afterwards.

**Comment by luijose** [comment]
Sure; feel free to publish it.. Thanks! :)

I'll update the README, and might add some other features as well.

**Comment by luijose** [comment]
Added correct documentation (87e3fb23). Will update NPM package.
