### ISSUE TITLE
Breaks on calling substr() on undefined

### ISSUE THREAD

**Issue by AHaymond** [luijose/hubot-9gag#2]
Line 41 in 9gag.coffee is breaking 90% of the time due to an undefined `img_src` variable.

**Comment by luijose** [comment]
This was due to a change in the DOM format for animated images. Fixed in latest commit (3ccba5e8).

**Comment by DonDebonair** [comment]
this is all nice and dandy, but this fix has not been released to NPM. So everyone following the README will end up with a non-working plugin :)
